### ISSUE TITLE
Does it support object-level permission like we have in `django-guardian`?

### ISSUE THREAD

**Issue by alexcmgit** [daveoconnor/graphene-field-permission#2]
Can we check for object-specific permissions by using `has_field_access` or `check_field_access`?

```py
user_123.has_perm('change_task', task_object_123)
```

There's a related post about this kind of permissions ([Permissions in Django - Object-level Permissions](https://testdriven.io/blog/django-permissions/)).

**Comment by daveoconnor** [comment]
I didn't need that so it doesn't support it but I could see why it's useful if you want to add it.
